# this is not a general makefile but something quick and dirty so I can actually run the debugger
# (I suck at raw makefiles, too much time using CMake that I'm out of touch :L)
all:
	gcc -g -O0 param_parser.c ../src/Parameters.c -I../include -o param_parser 
